# Configuração de Validação Científica
# FED-Selic Prediction Model

# Configurações gerais
general:
  data_path: "data/raw/fed_selic_combined.csv"
  output_dir: "reports/validation"
  figures_dir: "figures"
  registry_dir: "registry"
  
# Configurações de simulação
simulation:
  # Número de simulações Monte Carlo
  n_simulations: 1000
  
  # Tamanhos de amostra para testes
  sample_sizes: [25, 50, 75, 100, 200, 500]
  
  # Horizontes de previsão
  horizons: [1, 3, 6, 12]
  
  # Níveis de significância
  significance_levels: [0.01, 0.05, 0.10]
  
  # Tolerâncias para testes
  tolerances:
    size_test: 0.05
    power_test: 0.10
    small_sample: 0.08
    heteroskedasticity: 0.05

# Configurações de testes específicos
tests:
  size_power:
    # Alternativas para teste de poder
    alternatives: [0.95, 0.90, 0.80, 0.70, 0.50]
    
    # Configurações de heterocedasticidade
    hetero_configs:
      - name: "homoskedastic"
        description: "Variância constante"
        params: {}
      
      - name: "arch1"
        description: "ARCH(1)"
        params:
          alpha: 0.3
          beta: 0.0
      
      - name: "garch11"
        description: "GARCH(1,1)"
        params:
          alpha: 0.1
          beta: 0.8
      
      - name: "egarch"
        description: "EGARCH(1,1)"
        params:
          alpha: 0.1
          beta: 0.8
          gamma: 0.1

  structural_breaks:
    # Configurações de quebras estruturais
    break_configs:
      - name: "single_break"
        description: "Quebra única"
        break_points: [50]
        magnitudes: [1.0, 2.0, 3.0]
      
      - name: "double_break"
        description: "Duas quebras"
        break_points: [33, 67]
        magnitudes: [1.0, 1.5]
      
      - name: "triple_break"
        description: "Três quebras"
        break_points: [25, 50, 75]
        magnitudes: [1.0, 1.2, 0.8]

  small_samples:
    # Configurações para amostras pequenas
    small_sample_sizes: [10, 15, 20, 25, 30]
    
    # Métodos de correção
    correction_methods:
      - "none"
      - "bias_correction"
      - "bootstrap"
      - "bayesian"

  benchmarks:
    # Séries de Nelson-Plosser
    nelson_plosser_series:
      - name: "GDP"
        description: "Produto Interno Bruto"
        expected_order: 1
      
      - name: "UNEMPLOYMENT"
        description: "Taxa de Desemprego"
        expected_order: 1
      
      - name: "INTEREST_RATE"
        description: "Taxa de Juros"
        expected_order: 0
      
      - name: "PRICE_LEVEL"
        description: "Nível de Preços"
        expected_order: 1

  lag_selection:
    # Critérios de seleção de lags
    criteria: ["aic", "bic", "hqic", "fpe"]
    
    # Máximo de lags a testar
    max_lags: 12
    
    # Regra de Schwert
    schwert_rule: true

# Critérios de promoção (gates)
promotion_criteria:
  # Cobertura de intervalos de confiança
  min_coverage_80: 0.80
  min_coverage_95: 0.85
  
  # Calibração (ECE - Expected Calibration Error)
  max_ece: 0.10
  
  # Métricas de qualidade
  max_brier_score: 0.25
  max_crps: 0.30
  
  # Acurácia direcional
  min_directional_accuracy: 0.60
  
  # Estabilidade
  max_coefficient_instability: 0.20

# Configurações de relatórios
reporting:
  # Formato dos relatórios
  formats: ["markdown", "json"]
  
  # Incluir figuras
  include_figures: true
  
  # Nível de detalhe
  detail_level: "full"  # "summary", "full", "debug"
  
  # Incluir código
  include_code: true
  
  # Incluir dados
  include_data: false

# Configurações de CI/CD
ci:
  # Executar em PRs que toquem modelagem
  run_on_model_changes: true
  
  # Executar nightly
  run_nightly: true
  
  # Timeout em minutos
  timeout_minutes: 60
  
  # Retenção de artifacts (dias)
  artifact_retention_days: 30

# Configurações de reprodutibilidade
reproducibility:
  # Usar seeds fixos
  use_fixed_seeds: false
  
  # Salvar seeds
  save_seeds: true
  
  # Salvar hashes
  save_hashes: true
  
  # Verificar integridade
  check_integrity: true

# Configurações de performance
performance:
  # Usar paralelização
  parallel: true
  
  # Número de workers
  n_workers: 4
  
  # Usar cache
  use_cache: true
  
  # Cache TTL (horas)
  cache_ttl_hours: 24
